### ISSUE TITLE
When $user and $pass == null access is granted

### ISSUE THREAD

**Issue by ghost** [gonzalo123/token#1]
There is a small problem in the validation logic, the first access is granted because

`$user and $ pass == null`

It can (for educational purpose) add checks to the value null o method validateCredentials

//file:  LoginServiceProvider.php

```
    private function validateCredentials($user, $pass)
    {
        if ($user == null)
                return false; 

        if ($pass == null)
                return false;                 

        return $user == $pass;
    }
```

very good article!!!

**Comment by gonzalo123** [comment]
Yes. It's just an example. You must put there your login logic. 
The token generation/validation is similar.
